name: 'Read default versions JSON file'
description: 'Set default versions of F3D dependencies to install'
inputs:
  file:
    description: 'Local file to recover version information from'
    required: true
outputs:
  global_cache_index:
    value: "${{ fromJson(steps.parse_file.outputs.json).global_cache_index }}"
  docker_timestamp:
    value: "${{ fromJson(steps.parse_file.outputs.json).docker_timestamp }}"
  alembic_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.alembic }}"
  alembic_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.alembic }}"
  assimp_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.assimp }}"
  assimp_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.assimp }}"
  blosc_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.blosc }}"
  blosc_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.blosc }}"
  draco_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.draco }}"
  draco_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.draco }}"
  imath_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.imath }}"
  imath_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.imath }}"
  java_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.java }}"
  java_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.java }}"
  occt_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.occt }}"
  occt_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.occt }}"
  openexr_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.openexr }}"
  openexr_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.openexr }}"
  openvdb_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.openvdb }}"
  openvdb_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.openvdb }}"
  ospray_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.ospray }}"
  ospray_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.ospray }}"
  pybind11_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.pybind11 }}"
  pybind11_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.pybind11 }}"
  python_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.python }}"
  python_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.python }}"
  tbb_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.tbb }}"
  tbb_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.tbb }}"
  usd_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.usd }}"
  usd_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.usd }}"
  webp_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.webp }}"
  webp_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.webp }}"
  webifc_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.webifc }}"
  webifc_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.webifc }}"
  zlib_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).versions.zlib }}"
  zlib_min_version:
    value: "${{ fromJson(steps.parse_file.outputs.json).min_versions.zlib }}"
  vtk_commit_sha:
    value: "${{ fromJson(steps.parse_file.outputs.json).vtk_commit_sha }}"

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.file }}" ]] || { echo "file input is empty" ; exit 1; }

    - name: Read JSON file
      id: parse_file
      shell: bash
      run: |
        echo "json=$(jq -c . < ${{ inputs.file }})" >> $GITHUB_OUTPUT
